- build.gradle
- src/main/java/org/farmsystem/homepage/global/common/HealthCheckApi.java
- src/main/java/org/farmsystem/homepage/global/common/HealthCheckController.java
- src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
- src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
- src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
- close : #3 
- 프론트 로컬 주소 cors추가
- swagger config 관련 세팅 추가
- swagger 예시 작성(health check API,임시 토큰 API)
- 노션에 yml 업데이트 했습니다. (스웨거 설정 추가)
- 스웨거는 `{BaseUrl}/swagger`경로로 접속 가능합니다.
- 컨트롤러 로직이랑 문서화 코드 같이 쓰는 거보다 분리하는게 나을 거 같아서 명세 부분 인터페이스로 분리했는데 사용 예시는`/global/common/HealthCheckAPI` 랑 `/global/common/HealthCheckController` 확인해주시면 되겠습니다.
> [docs] swagger 세팅

- build.gradle
- src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsController.java
- src/main/java/org/farmsystem/homepage/domain/news/controller/NewsController.java
- src/main/java/org/farmsystem/homepage/domain/news/dto/request/NewsRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/entity/News.java
- src/main/java/org/farmsystem/homepage/domain/news/repository/NewsRepository.java
- src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
- close : #7 
- news 엔티티, 레포지토리 생성
- news 일반 사용자용 컨트롤러, 관리자용 컨트롤러 생성
- news 기본 기능 개발
- 이후에 관리자용 컨트롤러에 권한 제어 추가 필요함.
> [feat] NEWS 기본 기능

- src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsApi.java
- src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsController.java
- src/main/java/org/farmsystem/homepage/domain/news/controller/NewsApi.java
- src/main/java/org/farmsystem/homepage/domain/news/controller/NewsController.java
- src/main/java/org/farmsystem/homepage/domain/news/entity/News.java
- src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
- src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
- close : #7, #16 
- news 엔티티에 BaseTimeEntity 적용
- ErrorCode에 news 용 에러코드 추가
- NewsService에 news용 에러코드 적용
- news에 swagger-ui 적용
- `ErrorCode`가 많아지면 헷갈릴 것 같아서 news 섹션을 따로 나누고 에러 코드를 추가했는데, 코드별로 합칠까요, 기능별로 합칠까요? 
a. 기존 컨트롤러 메서드 반환 타입이 `ResponseEntity<SuccessResponse<?>>`로 되어있습니다. 
b. swagger 관련 인터페이스(`NewsApi`, `AdminNewsApi`)에서는 명시적 제네릭 타입으로 적용 (`ResponseEntity<SuccessResponse<List<NewsResponseDTO>>>`)하고 싶었으나,
c. 시그니처 불일치로 컴파일 오류가 났습니다. 
d. `SuccessResponse` 클래스가 `ResponseEntity<SuccessResponse<?>>`를 반환하고 있어 타입 추론하도록 하기 어려웠습니다.
e. 그래도 `SuccessResponse`를 유지하고 싶었고, 컨트롤러는 그대로 유지하게 되었습니다. 
f. 차선책으로 swagger 인터페이스만 수정했습니다. -> 인터페이스도 와일드카드 사용하도록 유지하되, `@ApiResponse의 @Schema(implementation = ...)`를 통해 실제 반환 DTO를 Swagger 문서에서 설명하는 방식으로 했는데
g. 이렇게 해도 될까요?
> [refactor] news BaseTimeEntity, 에러코드, swagger-ui

- build.gradle
- src/main/java/org/farmsystem/homepage/domain/apply/entity/PassedApply.java
- src/main/java/org/farmsystem/homepage/domain/apply/repository/PassedApplyRepository.java
- src/main/java/org/farmsystem/homepage/domain/user/controller/OauthController.java
- src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserInfoUpdateRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserLoginRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserTokenRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserVerifyRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserInfoResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserInfoUpdateResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserTokenResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserVerifyResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/entity/SocialType.java
- src/main/java/org/farmsystem/homepage/domain/user/entity/Track.java
- src/main/java/org/farmsystem/homepage/domain/user/entity/TrackHistory.java
- src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
- src/main/java/org/farmsystem/homepage/domain/user/repository/UserRepository.java
- src/main/java/org/farmsystem/homepage/domain/user/service/OauthService.java
- src/main/java/org/farmsystem/homepage/domain/user/service/OauthTokenProvider.java
- src/main/java/org/farmsystem/homepage/domain/user/service/OauthUserResourceProvider.java
- src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
- src/main/java/org/farmsystem/homepage/domain/user/service/UserService.java
- src/main/java/org/farmsystem/homepage/global/common/HealthCheckApi.java
- src/main/java/org/farmsystem/homepage/global/common/HealthCheckController.java
- src/main/java/org/farmsystem/homepage/global/common/S3Service.java
- src/main/java/org/farmsystem/homepage/global/config/RedisConfig.java
- src/main/java/org/farmsystem/homepage/global/config/S3Config.java
- src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
- src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
- close : #17  
- User 관련 기능 구현 (사용자 인증, 마이페이지 조회 및 수정 API)
- Oauth 관련 기능 구현 (카카오/구글 로그인, 리프레쉬토큰 재발급, 로그아웃)
- Redis, S3 관련 설정 및 연결
- 합격자 클래스 PassedApply , 트랙 기수 클래스 TrackHistory 새로 구현 (현재 기수는 User테이블에 한 번 더 저장하는 방식)
- 임시 토큰 -> 유저 엔티티로 이동
- 트랙 Enum 클래스 User랑 Apply에 둘 다 정의되어있는데 유틸 디렉토리에 옮기긴해야할 거 같음
- 회원 정보 관련 기능에 이메일 핸드폰 번호가 기능 명세 노션에 있어서 유저 엔티티에 추가 (회원정보 수정 가능불가능 정보 재확인 필요) 
- 로그인 트랙, 전화번호, 이메일 정보 어디서 가지고 오는지..? 합격자 테이블에는 해당 컬럼 없어서 지원서 테이블에서 가져와야할 거 같기도
- 합격자조회 API 아직 없는듯
- Oauth 쪽 지금 User, Token 등등 클래스 어떻게 분리할 지 매우 고민중 (코드 정리도 좀 필요할 듯)
<이후 작업>
- DTO validation 추가
- 스웨거 명세 추가
- Redis 배포 설정
- Oauth 리다이렉트 URL 배포 주소 설정 & YML분리 작업
> [feat] User & Oauth 관련 API 구현

- src/main/java/org/farmsystem/homepage/domain/user/entity/Role.java
- src/main/java/org/farmsystem/homepage/domain/user/entity/TrackHistory.java
- src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
- src/main/java/org/farmsystem/homepage/domain/user/repository/UserRepository.java
- src/main/java/org/farmsystem/homepage/domain/user/service/OauthService.java
- src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
- src/main/java/org/farmsystem/homepage/global/config/RedisConfig.java
- src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
- src/main/java/org/farmsystem/homepage/global/config/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/org/farmsystem/homepage/global/config/auth/jwt/JwtProvider.java
- close : #26 #25
1. `Role` 엔티티 추가 후, `Spring Security`에 리소스 제어
2. jwt 관련 코드에 `Role` 정보 함께 담도록 수정
1. `Optional`
`UserRepository.findByStudentNumber()`가 `Optional<User>`을 반환하도록 수정
2. `redisTemplate` 관련 이슈
- `TokenService`가 어떤 빈을 사용해야 할 지 몰라서 에러 발생함.
- Spring Boot가 제공하는 `StringRedisTemplate`이 자동으로 빈으로 등록되어있었음
- 우리가 만든 `redisTemplate`도 동시에 존재해서 에러 발생함
- `redisTemplate`에 `@Primary` 추가하여 이 템플릿을 기본 빈으로 설정함
3. `generation `타입 수정
- 각 클래스에서 `generation`을 보면
- `User`에는 `nullable=true`, `int`로 되어있는데,
- `TrackHistory`에는 `nullable=false`, `int`로 되어있었음.
- 위 사항이 자꾸문제를 발생시켜서 `Integer`로 통일함.
@floreo1242 
@hysong4u 
`SecurityConfig` 확인 ->  `/api/admin`하위 경로만 관리자 페이지로 인식함.
✅ To-Do
1. 본인이 맡은 API 개발하되, 관리자 API는 앞에 '`Admin`'을 붙인다. 
e.g. `NewsApi `-> `AdminNewsApi`
2. 경로를 `/api/admin`으로 설정한다.
3. Test
관리자 권한을 가진 …
> [feat] #26 관리자 권한 

- src/main/java/org/farmsystem/homepage/domain/apply/controller/ApplyController.java
- src/main/java/org/farmsystem/homepage/domain/apply/dto/AnswerDTO.java
- src/main/java/org/farmsystem/homepage/domain/apply/dto/request/ApplyRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/apply/dto/request/CreateApplyRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/apply/dto/request/LoadApplyRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/apply/dto/response/CreateApplyResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/apply/dto/response/LoadApplyResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
- src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatus.java
- src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatusEnum.java
- src/main/java/org/farmsystem/homepage/domain/apply/exception/AnswerNotFoundException.java
- src/main/java/org/farmsystem/homepage/domain/apply/exception/ApplyAlreadySubmittedException.java
- src/main/java/org/farmsystem/homepage/domain/apply/exception/ApplyNotFoundException.java
- src/main/java/org/farmsystem/homepage/domain/apply/exception/ChoiceNotFoundException.java
- src/main/java/org/farmsystem/homepage/domain/apply/exception/QuestionNotFoundException.java
- src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
- src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyStatusRepository.java
- src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
- src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
- src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
- close : #20 
- 개별 Exception 클래스 삭제
- 에러코드 메시지 수정
- 임시저장 비밀번호 암호화
- DTO Validation 추가
- 중복 제출 방지를 위한 ApplyStatus 엔티티 추가
- 이에 따라 기존 ApplyStatus 열거형은 ApplyStatusEnum으로 변경
- 요구사항에 맞게 세부 로직 수정
- 기존 개인정보 생성 API은 지원서 생성 API로 변경
- 임시저장, 제출 API에서 지원서 내용과 함께 개인정보도 추가로 저장
- `아직 작성하지 않은 질문은 빈 텍스트로 요청`에서 `작성하지 않은 질문은 요청하지 않음` 으로 바뀜에 따라 임시저장 시 기존 답변이 없다면 생성 후 수정하도록 로직 추가
- apply 테이블에 학번, 비밀번호로 UNIQUE 제약조건 설정
- 제출 시 Apply의 status가 `SUBMITTED`가 되는건 단순 명시용으로, 중복 제출 여부는 ApplyStatus에 해당 학번이 존재하는지로 확인합니다.
> [feat] 지원 추가 구현

- src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
- src/main/java/org/farmsystem/homepage/domain/apply/entity/ApplyStatus.java
- src/main/java/org/farmsystem/homepage/domain/apply/entity/Choice.java
- src/main/java/org/farmsystem/homepage/domain/apply/entity/Question.java
- src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
- src/main/java/org/farmsystem/homepage/domain/apply/repository/QuestionRepository.java
- src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
- src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
- close : #43 
1. 트랙으로 정렬 후 priority 정렬
2. Choice 엔티티에 priority 추가
3. Question의 선택지 조회 시 항상 priority 오름차순으로 조회 하도록 설정
1. Apply 엔티티의 NOT NULL이 아니어야 하는 column에 @Column nullable=false 옵션 삭제
2. Salt로 인해 UNIQUE 제약조건이 작동하지 않음 -> 지원서 생성 시 비밀번호 대조 후 에러 발생
> [feat] 지원 priority 구현 및 버그 수정

- src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
- close : #56 
corsConfig에 서버쪽 서브도메인 주소 추가
- yml업데이트
- 이전 pr에서 스웨거 https로 호스팅되게 수정했으나 여전히 GET을 제외한 http method사용하는 API에서 cors 문제 발생. 아래 블로그 우리랑 비슷한 상황인거 같아서 참고해서 수정했으나 개발 환경 테스트 필요 (로컬에서는 스웨거 cors 테스트할 수 있는 방법이,,,,)
(참고)
https://minseok-study.tistory.com/entry/JAVASPRING-BOOT-swagger-POST-PUT-PATCH-403-%EB%AC%B8%EC%A0%9C-%ED%8A%B8%EB%9F%AC%EB%B8%94-%EC%8A%88%ED%8C%85-springdoc
> [fix] 스웨거 배포 주소 cors 에러 수정

- src/main/java/org/farmsystem/homepage/domain/apply/entity/Answer.java
- src/main/java/org/farmsystem/homepage/domain/apply/entity/Choice.java
- src/main/java/org/farmsystem/homepage/domain/apply/entity/Question.java
- src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java
- src/main/java/org/farmsystem/homepage/domain/apply/repository/QuestionRepository.java
- src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
- close : #47 
- Service 메서드마다 주석 추가
- NOT NULL인 priority 필드 int 사용, nullable false 명시
- 지원서 불러오기 시, 학번을 List로 불러와서 비밀번호 일치하는 엔티티 사용 하도록 변경
- 기존에는 Optional로 불러와 두개 이상 존재시 에러 발생했음
- N+1 관련 코드 개선
-  Question 조회 시, Choice에 EntityGraph로 fetch join 적용
- Apply 조회 시, Answer는  EntityGraph로 fetch join, 각 Answer에 대한 AnswerChoice는 BatchSize(5)로 조회
> [ refactor ] 지원 N+1 문제 관련 코드 개선

- src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsApi.java
- src/main/java/org/farmsystem/homepage/domain/news/controller/AdminNewsController.java
- src/main/java/org/farmsystem/homepage/domain/news/controller/NewsApi.java
- src/main/java/org/farmsystem/homepage/domain/news/controller/NewsController.java
- src/main/java/org/farmsystem/homepage/domain/news/dto/request/NewsRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsDetailResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsListResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/entity/News.java
- src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
- close : #89 
- 썸네일 이미지 추가
- 본문 이미지들 추가
- 전체 조회용 NewsListResponseDTO, 단일 조회용 NewsDetailResponseDTO 분리
- 소식 관련 컬럼 전부 수정할 수 있도록 updateNews로 변경
> [feat] news 이미지 추가

- src/main/java/org/farmsystem/homepage/domain/apply/dto/response/SubmittedApplyResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
- close : #101 
지원서 상세 확인 시 제출 트랙의 답변만 반환하도록 수정
- SubmittedApplyResponseDTO 생성
- filter() 통해 answer의 track 이 apply의 track과 같은 answer만 response에 포함
> [fix] #101 지원서 상세 확인 시 제출 트랙의 답변만 반환하도록 수정

- .github/CODEOWNERS
- close : #108
- BE 레포 자동 리뷰어 지정
- 하위팀이 안 만들어져서 일단은 개인 아이디로 지정했는데 나중에는 파트별 하위팀 만들어서 팀 멘션&팀 리뷰어 관리하면 좋지않을까라는 생각!
> [chore] BE 레포 자동 리뷰어 지정

- src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerApi.java
- src/main/java/org/farmsystem/homepage/domain/cheer/service/CheerService.java
- src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
- close : #121 
에러코드 SAME_CHEERED_CHEERED 추가
cheererId와 cheeredId가 같을 때 에러 발생
API 문서에 실패 예시 추가
프론트에서도 응원할 사용자 검색 시 자기 자신 안나오게 걸러주면 좋을 것 같습니다!!
> [feat] #121 cheered와 cheerer가 같을 경우 에러 발생

- src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerController.java
- src/main/java/org/farmsystem/homepage/domain/cheer/service/CheerService.java
- src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
- src/main/java/org/farmsystem/homepage/domain/notification/controller/NotificationApi.java
- src/main/java/org/farmsystem/homepage/domain/notification/dto/NotificationResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/notification/event/CheerReceiveEvent.java
- src/main/java/org/farmsystem/homepage/domain/notification/event/FarmingLogLikedEvent.java
- src/main/java/org/farmsystem/homepage/domain/notification/event/NotificationEventListener.java
- src/main/java/org/farmsystem/homepage/domain/notification/service/NotificationService.java
- src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
- close : #126 
- 응원하기 등록, 파밍로그 좋아요 시 알림 이벤트 생성 및 전송
- 응원하기 개별 조회 기능 추가
- @saokiritoni  파밍로그 좋아요 토글 서비스에서 좋아요를 했을 때에만 알림이 가도록 하기 위해 코드 조금 수정했으니 확인해주세요!!
> [feat] 알림 전송 코드 추가

- src/main/java/org/farmsystem/homepage/domain/user/controller/UserApi.java
- src/main/java/org/farmsystem/homepage/domain/user/controller/UserController.java
- src/main/java/org/farmsystem/homepage/domain/user/dto/response/TodaySeedResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
- src/main/java/org/farmsystem/homepage/domain/user/service/TokenService.java
- close : #131 
- 기존 엑세스 토큰 재발급시 리프레쉬 토큰도 재발급 되는 문제 해결
=> 리프레쉬 재발급 코드 삭제 후 레디스에 저장된 기존 토큰을 반환합니다.
- 오늘의 씨앗 적립 조회 API 구현 (출석, 응원, 파밍로그)
> [ feat ] 오늘의 씨앗 적립 현황 표시 & 토큰 재발급 API 수정

- src/main/java/org/farmsystem/homepage/domain/user/service/UserService.java
- close : #135 
유저 새로 생성했을 때 내 랭킹 null 오류 원인은 
- `userRankList` 랭킹 리스트 데이터는 0시에 업데이트되는 캐싱 데이터  
- `myRank` 는 위 userRankList 데이터에서 내 랭크를 찾는 방식
인데 캐싱된 랭킹리스트에 새로 만든 유저정보가 없으니까(이거는 원래 12시에 업데이트 반영) null로 들어감!
- 멤버가 새로 생길 때 랭킹 임의로 업데이트 해버리면 캐싱된 데이터를 사용하고 있는 다른 유저와 랭크데이터 싱크가 안 맞는 문제 발생
- 변경시 매번 캐싱 데이터 업데이트 하더라도 업데이트의 범위를 정해야함! (유저가 생성될때 or 씨앗이 적립될 때 or 프로필 이미지 등 랭크에 보여지는 정보  등 중 하나라도 변경이 생겼을 때)
- 대안으로는 유저 생성시 해당 유저는 랭킹에 추가하고(이 시간 동안은 안 맞을 수 있음) 다른 유저를 포함한 랭킹 업데이트 주기는 좀 더 짧게 가져가기 등의 방법이 있을 거 같음
일단 위 방안에 대해서 논의가 좀 더 필요할 거 같아서 현재는 단순하게 유저가 생성될 때 캐싱 데이터 삭제 하는 방식을 사용함 
=> 유저 생성 될 때 마다 캐싱 데이터 안쓰고 쿼리 조회문으로 가져옴
> [fix] #135 유저 새로 생성될 때 기존 랭킹 캐시 삭제

- src/main/java/org/farmsystem/homepage/domain/farmingLog/entity/FarmingLogLike.java
- src/main/java/org/farmsystem/homepage/domain/farmingLog/repository/FarmingLogLikeRepository.java
- src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java
- src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogService.java
- src/main/java/org/farmsystem/homepage/domain/notification/entity/Notification.java
- close : #138 
- Notification 엔티티 title length 20으로 조정
- 파밍로그 좋아요 기록에 soft delete 적용
- 첫 좋아요인 경우, 자기 자신의 파밍로그가 아닌 경우에만 알림 전송
- 좋아요 취소 시 파밍로그 좋아요 매핑 테이블에 is_deleted true로 표시하고, 어떤 기록도 없을 경우에만 알림 전송하도록 함
> [bug] 알림 title 길이 제한, 파밍로그 알림 전송 조건

- src/main/java/org/farmsystem/homepage/domain/news/dto/request/NewsRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsDetailResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsListResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
- close : #89 
- 뉴스에 이미지 추가
- 문서 작성
- 뉴스 리스트에 내용 50자 반환 추가
- 모든 뉴스 response에 createdAt, updatedAt 추가
> [refactor/feat] 뉴스 반환값 수정

- Dockerfile
- close : #151
-Xmx256m | 최대 힙 메모리를 256MB로 제한
-Xms128m | 초기 힙 메모리 크기를 128MB로 설정
</div></div>
> [fix] JVM 힙 메모리 제한 추가

- src/main/java/org/farmsystem/homepage/domain/user/service/DailySeedService.java
- close : #148
getTodaySeed 메서드는 조회 용도로 사용되는 트랜잭션이지만 중복요청 방지용을 @Lock을 걸어두면서 PESSIMISTIC_WRITE (FOR UPDATE)를 포함하는 쿼리를 실행함 -> Transactional ReadOnly 에러가 발생 -> @Transactional 덮어써서 해결
> [fix] @Lock으로 인해 발생한 READ ONLY 트랜잭션 오류 해결

- src/main/java/org/farmsystem/homepage/domain/user/controller/AuthApi.java
- src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
- 이전에 작성한 @Profile은 swagger명세 작성한 인터페이스에서 동작을 안함 
- @Hidden으로도 특정 API를 숨길 수 있으나 특정 환경에서의 적용은 안됨 (스웨거는 동적 생성인데  @Hidden은 정적 어노테이션이어서인듯)
=> 특정 API 명세를 특정 환경에서 숨기기 위한 조건부 Bean 등록 추가
> [docs] 운영환경 임시토큰 발급 API Swagger 문서에서 제거

- src/main/java/org/farmsystem/homepage/domain/minigame/player/controller/PlayerController.java
- src/main/java/org/farmsystem/homepage/domain/minigame/player/dto/PlayerCurrencyDTO.java
- src/main/java/org/farmsystem/homepage/domain/minigame/player/dto/request/LevelUpdateRequestDTO.java
- src/main/java/org/farmsystem/homepage/domain/minigame/player/dto/response/PlayerResponseDTO.java
- src/main/java/org/farmsystem/homepage/domain/minigame/player/entity/Player.java
- src/main/java/org/farmsystem/homepage/domain/minigame/player/service/PlayerService.java
- close : #170 
- 플레이어 엔티티에 seedCount 필드 추가
- 플레이어 재화 업데이트 api 변경 (seedCount 추가, 요청/응답 dto의 변수명 수정)
- 플레이어 레벨 업데이트 api 추가
- 플레이어 조회 api에 유저아이디, 플레이어 아이디 제외하도록 수정
> [fix] #172 Player 관련 api 수정, 추가

- src/main/java/org/farmsystem/homepage/domain/minigame/farm/entity/PlantStatus.java
- src/main/java/org/farmsystem/homepage/domain/minigame/farm/service/FarmService.java
- src/main/java/org/farmsystem/homepage/domain/minigame/player/service/DailyGameService.java
- src/main/java/org/farmsystem/homepage/domain/minigame/solarstation/controller/SolarController.java
- src/main/java/org/farmsystem/homepage/domain/minigame/solarstation/dto/SolarDTO.java
- src/main/java/org/farmsystem/homepage/domain/minigame/solarstation/entity/SolarPowerStation.java
- src/main/java/org/farmsystem/homepage/domain/minigame/solarstation/service/SolarService.java
- close : #175
- Farm, SolarStation, DailyGame 서비스 메서드에서 @Transactional(readOnly = true) 제거하여 신규 엔티티 생성 시 insert 실행 가능하도록 수정
- Dex/Badge 등 조회 전용 메서드에는 readOnly 유지
- SolarStation에서 level제거
> [fix] 엔티티 생성 시 readOnly 트랜잭션으로 인한 insert 오류 수정
