Dockerfile
=> [chore] Dockerfile 작성

.github/workflows/main.yml, src/main/resources/application.yml
- close : #8 
- application.yml 환경변수 넣어서 수정
- 워크플로우 작성
notion 참고
=> [ chore ] CI/CD 설정 - application.yml 및 워크플로우

.github/workflows/main.yml
- close : #8
main 브랜치만 배포하도록 수정
=> [fix] #8 main 브랜치만 배포하도록 수정

src/main/java/org/farmsystem/homepage/HomePageBeApplication.java, src/main/java/org/farmsystem/homepage/global/common/BaseTimeEntity.java
/global/common 디렉토리에 BaseTimeEntity 추가했습니다.
- 일단은 날짜 필드 타입 LocalDateTime인데 TimeStamp로 변경 가능
- 다른 엔티티 클래스에서 사용할 때는 createdAt updatedAt 따로 필드명 선언 없이 날짜 필요한 엔티티 클래스에서 상속해서 사용하면 됩니다.
ex) public class User extends BaseTimeEntity{}
=> [feat] BaseTimeEntity 구현

.github/workflows/dev-cicd.yml, .github/workflows/prod-cicd.yml
- close : #22
- prod-cicd.yml
- dev-cicd.yml
=> [chore] - 서버분리 CI/CD 적용

.github/workflows/dev-cicd.yml, .github/workflows/prod-cicd.yml
- close : #22
- Production, Development CI/CD 스크립트 작성
- GitHub Secret 설정
- 본 PR을 머지 함으로써 prod-cicd.yml 테스트 
- release/v0.0.1 브랜치 생성 후 dev-cicd.yml 테스트 완료함
- production 블루/그린
- deprecated된 명령어 사용한 것 같아서 그거 수정
=> [chore] #22 서버분리 CI/CD

.github/workflows/prod-cicd.yml
=> [fix] #22 Production CI/CD 스크립트 수정

src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
- close : #49 
cors 프론트 배포 주소 추가
=> [chore] #49 cors 프론트 배포 주소 추가

src/main/java/org/farmsystem/homepage/domain/apply/entity/Apply.java
- close : #67 
지원서 학번 유니크 제약조건 삭제
=> [fix] 지원서 학번 유니크 제약조건 삭제

src/main/java/org/farmsystem/homepage/domain/user/service/OauthTokenProvider.java, src/main/java/org/farmsystem/homepage/domain/user/service/OauthUserResourceProvider.java
- close : #72 
기존에 e.printStackTrace(); 사용했더니 로컬에서는 로그가 찍히는데 배포 버전에서 표시가 안되는 거 같음
=> @slf4j 사용 방식으로 변경
=> [refactor] 로그 표시 방식 변경

.github/ISSUE_TEMPLATE/--bug----bug-report.md, .github/ISSUE_TEMPLATE/--refactor-----refactoring-request.md
- close : #61 
- 이슈 템플릿 제목 뒤에 '-' 붙는 거 삭제 (제목 컨벤션 통일용)
=> [docs] 이슈 템플릿 제목 수정

src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
- close : #7 
뉴스 api 토큰 없이 접근하도록 수정
이겨냈다.
=> [fix] whitelist 수정

src/main/java/org/farmsystem/homepage/domain/apply/controller/AdminApplyApi.java, src/main/java/org/farmsystem/homepage/domain/apply/controller/AdminApplyController.java, src/main/java/org/farmsystem/homepage/domain/apply/dto/response/ApplyListResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/repository/ApplyRepository.java, src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
- close : #71 
- 지원서 목록, 상세 API 구현 (관리자용)
- 일단 이거 먼저 올리고 질문 수정하기 마저 올릴게요
=> [feat] 지원서 확인 API

src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java
- close : #49
corsConfig에 프론트 파밍로그 dev, prod 주소 추가
=> [chore] cors 추가

src/main/java/org/farmsystem/homepage/domain/user/dto/request/UserLoginRequestDTO.java
- close : #97
enum 타입인 socialType에 대해서 @NotBlank->NotNull로 수정
enum타입에서 @NotBlank 안된다니
=> [fix] validation 변경

src/main/java/org/farmsystem/homepage/domain/apply/dto/QuestionDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/dto/response/ApplyListResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/dto/response/LoadApplyResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
- close : #101 
- 지원서 확인 응답에 학번 추가
- 이걸 develop에 할지 바로 1.0.1에 올릴지 고민이네.. 어차피 소은이가 1.0.1에 바로 수정한거 올릴거니까..
- 일단 develop으로 해놓을게
=> [fix] #101 지원서 확인 API에 학번 추가

src/main/java/org/farmsystem/homepage/domain/apply/dto/QuestionDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/dto/response/ApplyListResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/dto/response/LoadApplyResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/dto/response/SubmittedApplyResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/service/ApplyService.java
- close : #101 
- release 수정 이후 merge
=> [deploy] v1.0.1에 #101, #104 반영

src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogLikeService.java, src/main/java/org/farmsystem/homepage/domain/farmingLog/service/FarmingLogService.java, src/main/java/org/farmsystem/homepage/global/config/CorsConfig.java, src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
- Compile Error - ',' 추가
- 잘못된 ErrorCode 수정
- localhost:3000 추가
- application.yml update 사항 있습니다!
=> [deploy] release/v1.0.1에 에러 수정

src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerApi.java, src/main/java/org/farmsystem/homepage/domain/cheer/controller/CheerController.java, src/main/java/org/farmsystem/homepage/domain/cheer/dto/request/CheerRequestDTO.java, src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/CheerResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/CheerUserDTO.java, src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/PagingCheerListResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/cheer/entity/Cheer.java, src/main/java/org/farmsystem/homepage/domain/cheer/entity/CheerTag.java, src/main/java/org/farmsystem/homepage/domain/cheer/repository/CheerRepository.java, src/main/java/org/farmsystem/homepage/domain/cheer/service/CheerService.java, src/main/java/org/farmsystem/homepage/domain/user/entity/User.java
- close : #54 
- 응원 등록 기능
- 응원 조회 기능
- 응원 조회 기능은 하연이 만들어준 PageResponse 사용했는데 맞는지 확인 부탁이요!!
=> [feat] 응원하기

src/main/java/org/farmsystem/homepage/domain/cheer/dto/response/PagingCheerListResponseDTO.java
=> [fix] 컴파일 에러 방지 위해 pageResponseDTO 위치 변경

src/main/java/org/farmsystem/homepage/domain/apply/controller/AdminPassedApplyApi.java, src/main/java/org/farmsystem/homepage/domain/apply/dto/response/PassedApplyRegisterResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/apply/service/PassedApplyService.java, src/main/java/org/farmsystem/homepage/domain/common/entity/Track.java, src/main/java/org/farmsystem/homepage/domain/project/dto/response/ProjectPageResultDTO.java, src/main/java/org/farmsystem/homepage/global/error/ErrorCode.java
- close : #106 
- csv파일 합격자 리스트 등록 API 구현
- 기존 합격자 개별 등록 API 도메인 위치 이동(User-> PassedApply)
- csv 파일 형식에 따라 매핑하는 필드명 수정 필요합니다
- 트랙명 한글로 저장하면 Enum 매핑 추가 필요합니다
=> [feat] csv파일로 합격자 정보 저장하기

.github/workflows/dev-cicd.yml
=> [chore] 블루/그린 배포

.github/workflows/prod-cicd.yml
=> [chore] #128 main 브랜치에 대한 블루/그린 반영

src/main/java/org/farmsystem/homepage/domain/user/dto/response/UserRankResponseDTO.java
- close : #139
- 깃허브, 전공 정보 추가
=> [refactor] Ranking API에 response 추가

src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
- close : #145 
해당 Pull Request에서 수행한 작업 목록을 제시해야 합니다.
SecurityConfig whitelist에 응원 API 추가
=> [fix] SecurityConfig 응원 API 엔드포인트 추가

src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
=> [fix] SecurityConfig 화이트리스트에 응원 API 엔드포인트 삭제

Dockerfile, src/main/java/org/farmsystem/homepage/domain/news/dto/request/NewsRequestDTO.java, src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsDetailResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsListResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java, src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
#147, #150, #152
v1.1.3 테스트 서버에 반영
=> [deploy] update release/v1.1.3

src/main/java/org/farmsystem/homepage/domain/news/dto/request/NewsRequestDTO.java, src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsDetailResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsListResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/news/entity/News.java, src/main/java/org/farmsystem/homepage/domain/news/service/NewsService.java
=> [feat] 태그 추가

src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsDetailResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/news/dto/response/NewsListResponseDTO.java, src/main/java/org/farmsystem/homepage/global/config/auth/SecurityConfig.java
- close : #89 
- 뉴스 API 문서 보충
- 프로젝트 whitelist 추가
=> [docs/fix] 뉴스 API 문서 보충, 프로젝트 whitelist 추가

src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
- close : #160 
- SwaggerConfig에 Profile 어노테이션 적용으로 로컬, 개발 환경에서만 스웨거 노출
=> [feat] #160 Swagger에 Profile 설정 추가

src/main/java/org/farmsystem/homepage/domain/blog/entity/Blog.java, src/main/java/org/farmsystem/homepage/domain/project/entity/Project.java
- close : #167 
blog, project 링크 및 content 부분 columnDefinition = "TEXT"로 수정
죄송합니다..
=> [fix] 글자수 제한(255) 수정

src/main/java/org/farmsystem/homepage/global/config/SwaggerConfig.java
=> [feat] Swagger 설정에 JWT 보안 요구사항 추가

src/main/java/org/farmsystem/homepage/domain/minigame/farm/controller/FarmController.java, src/main/java/org/farmsystem/homepage/domain/minigame/farm/dto/request/TileUpdateRequest.java, src/main/java/org/farmsystem/homepage/domain/minigame/farm/entity/PlantedPlant.java, src/main/java/org/farmsystem/homepage/domain/minigame/farm/service/FarmService.java
- close : #173 
- 비즈니스 메서드를 엔티티에 추가
- DTO에 validation을 추가
- 서비스 계층에서 setter 사용 지양
- SuccessResponse 통일
=> [refactor] #175 Farm 도메인 리뷰 피드백 반영

src/main/java/org/farmsystem/homepage/domain/minigame/farm/controller/FarmController.java, src/main/java/org/farmsystem/homepage/domain/minigame/farm/dto/request/TileUpdateRequestDTO.java, src/main/java/org/farmsystem/homepage/domain/minigame/farm/dto/response/FarmResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/minigame/farm/dto/response/TileResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/minigame/farm/entity/PlantedPlant.java, src/main/java/org/farmsystem/homepage/domain/minigame/farm/service/FarmService.java
- close : #173 
- DTO 파일들을 rename
- 코드 설명 주석 추가
=> [rename] #175 Farm 도메인 DTO 파일명에 DTO 추가

src/main/java/org/farmsystem/homepage/domain/minigame/inventory/entity/Store.java
- close : #[Issue number]
- 게임팀 요구사항에 맞춰, Store 엔티티에 필드 추가
=> [fix] #194 Store 엔티티 필드 추가

src/main/java/org/farmsystem/homepage/domain/blog/controller/AdminBlogController.java, src/main/java/org/farmsystem/homepage/domain/blog/controller/BlogController.java, src/main/java/org/farmsystem/homepage/domain/blog/controller/docs/AdminBlogApi.java, src/main/java/org/farmsystem/homepage/domain/blog/controller/docs/BlogApi.java, src/main/java/org/farmsystem/homepage/domain/blog/dto/request/BlogRequestDTO.java, src/main/java/org/farmsystem/homepage/domain/blog/dto/response/BlogApprovalResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/blog/dto/response/BlogResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/blog/dto/response/MyApplicationResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/blog/dto/response/PendingBlogResponseDTO.java, src/main/java/org/farmsystem/homepage/domain/blog/service/AdminBlogService.java, src/main/java/org/farmsystem/homepage/domain/blog/service/BlogService.java
- close : #197 
- 블로그 DTO & 서비스 & 컨트롤러 정리
- 블로그 사용자/관리자 API 문서 작성
- 관리자 블로그 게시 API 추가
23048210941802년만의 PR.😉
=> [refactor] 블로그

.github/workflows/dev-cicd.yml, .github/workflows/prod-cicd.yml
=> [feat] #205 사용하지 않는 도커 이미지를 정리하도록 수정
